### ISSUE TITLE
How to load previous initial points already done?

### ISSUE THREAD

**Issue by nikorose87** [ppgaluzio/MOBOpt#3]
Hi, 
I am running very expensive functions and MOBOpt would be very useful only if I could load previous initial points to run the optimization.

Also, it would be nice to be able to resume an optimization problem.

**Comment by ppgaluzio** [comment]
This is a change I've been meaning to implement. Check out the `initpoint` branch, I made the appropriate changes at the `initialize` method there. I ran some tests and I believe they are working perfectly fine.

**Comment by nikorose87** [comment]
I have just pulled it. I am giving a try. I will let you know If it worked.

**Comment by nikorose87** [comment]
It is working so far, thanks. 
By the way, How many dimensions, as maximum, can I used is this algorithm in order to get reliable results?

**Comment by ppgaluzio** [comment]
Great to know! I'll just update the documentation and merge the change to master then.
Well, the larger the dimension of the search the more points you will need in order for the algorithm to converge. I tested some benchmarks with up to ten dimensions. It worked well as long as the Pareto front is well behaved, discontinuouties in the PF require more iterations, it is feasible, but starts to get slow . One intention is to change the scikit-learn implementation of the GP by GPytorch, presumably it is more efficient, particularly for large dimensions.

**Comment by CuiHen** [comment]
I think for future references, a more detailled documentation might be good. For me at least, I got two major insights for a successful loading:   

- When resuming the optimization problem, it is possible to set `init_points=None` so no additional reference points are sampled at the beginning.  
- The more important part:  When `MOBayesianOpt` is called with `max_or_min='min'`, the `Y` parameter in `initialize(self, init_points=None, Points=None, Y=None)` should be negated as well. Otherwise the observation points are wrongly loaded and the Bayesian optimizater will break
